name: .NET

on:
  push:
    branches: [ main develop release +/hotfix/** features/backend* ]
  pull_request:
    branches: [ main develop release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Move to Backend dir
      run: cd .\Backend; ls
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
